# Config file to define all available selections
# Selections contain object- and event-level cuts
# Previously defined selections can be imported with '<<' or '*'
# Any nested lists created by "<<" or '*' operations will be flattened in sidm_processor.py


# basic analysis selections
base: &base
  obj_cuts: &obj_base
    pv: &pv_base
      - "ndof > 4"
      - "|z| < 24 cm"
      - "|rho| < 0.2 mm"
    ljsource: &lj_base
      - "pT > 30 GeV"
      - "|eta| < 2.4"
  evt_cuts: &evt_base
    - "PV filter"
    - "Cosmic veto"
    - ">=2 LJs"

4mu: &4mu
  << : *base
  evt_cuts: &evt_4mu
    - *evt_base
    - "4mu"

2mu2e: &2mu2e
  << : *base
  evt_cuts: &evt_2mu2e
    - *evt_base
    - "2mu2e"

# basic analysis selections with no LJ pT cut
noLjPtCut: &noLjPtCut
  << : *base
  obj_cuts:
    << : *obj_base
    ljsource:
      - "|eta| < 2.4"

4mu_noLjPtCut: &4mu_noLjPtCut
  << : *noLjPtCut
  evt_cuts:
    - *evt_base
    - "4mu"

2mu2e_noLjPtCut: &2mu2e_noLjPtCut
  << : *noLjPtCut
  evt_cuts:
    - *evt_base
    - "2mu2e"
