# config to store info on composite datasets

DYJetsToMuMu:
  - DYJetsToMuMu_M10to50
  - DYJetsToMuMu_M50

QCD:
  - QCD_Pt15To20
  - QCD_Pt20To30
  - QCD_Pt30To50
  - QCD_Pt50To80
  - QCD_Pt80To120
  - QCD_Pt120To170
  - QCD_Pt170To300
  - QCD_Pt300To470
  - QCD_Pt470To600
  - QCD_Pt600To800
  - QCD_Pt800To1000
  - QCD_Pt1000

TTJets:
  - TTJets

Background:
  - DYtoMuMu
  - QCD
  - TTJets